version: '3'
services:
  web:
    build: .
    image: joke-scheduler-docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      TYPEORM_HOST: postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: joke_scheduler
